### PR TITLE
Support for Rock Candy Xbox One gamepad

### PR DESCRIPTION
**Pull request by Fenisu**
Support for upgraded version of Logic3 Rock Candy Gamepad for Xbox One.

### CODE REVIEW

**Comment by Plagman** [comment]
We just pushed a Beta update including a kernel diff that I think is a superset of this PR. Can you check if your Rock Candy works with 2.55?

**Comment by JoshuaMurphynz** [comment]
You can't download 2.55. Brewmaster is 2.49 and brewmaster_beta is 2.59

**Comment by Plagman** [comment]
Thanks for the correction, 2.59 has the change I was referring to.

**Comment by Fenisu** [comment]
It works perfectly now. Thanks for your hard work.

**Pull request closed without merging**
