### PR TITLE
Brewmaster 4.1

### PR DESCRIPTION
**Pull request by fledermaus**
Linux 4.1 + valve patches

### CODE REVIEW

**Comment by johnv-valve** [comment]
seeing tons of conflicts here

**Comment by Tele42** [comment]
If it's not too much trouble, there is a request at https://github.com/ValveSoftware/SteamOS/issues/406 to add a trivial patch to detect Killer NIC E2400, should be an easy review.

**Comment by fledermaus** [comment]
On Mon, 2 Nov 2015, johnv-valve wrote:

> seeing tons of conflicts here

Shouldn't be any - I'll check the branches.

**Comment by fledermaus** [comment]
On Mon, 2 Nov 2015, johnv-valve wrote:

> seeing tons of conflicts here

It's the final commit on that branch: 6efd2d003736dc97634feea34c529a35c75aa0d3
pull goes cleanly onto the commit before that (there's a ton of stuff in 
the tip of steamos/brewmaster-4.1)

If there's important stuff in there I can go through it but it's not in
the current brewmaster 4.1 kernel package.

**Pull request closed without merging**
